name: mopper_env
channels:
  - conda-forge

dependencies:
  - anaconda-client
  - conda-build
  - conda-verify
  - python #=3.11
  - click
  - xarray>=2024.05.0
  - cmor  #=3.13.0
  - numpy
  - dask
  - pyyaml
  - cftime
  - python-dateutil
  - metpy
  - gsw
  - pytest
  - pyfakefs
  - coverage
  - codecov
