# this workflow can be used as a template for a worklfow
# that runs automatically only specific tests when pushing 
# to a selected branch. 
name: mopper-specific-tests

on: 
  push:
    branches:
      - class

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.10/3.11
      uses: actions/setup-python@v5.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        activate-environment: testenv
        environment-file: conda/testenv.yaml
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Lint with ruff
      shell: bash -el {0}
      run: |
        ruff check --output-format=github .
      continue-on-error: true
     
    # making sure we are testing installed package
    - name: Install package
      shell: bash -el {0}
      run: |
        conda activate testenv
        pip install  -e .
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        conda run python -m pytest -q tests/test_calculations.py
