name: Test Build of mopper conda package

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the prerelase branch
  push:
    branches: [ prerelease ]
  pull_request:
    branches: [ prerelease ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Test conda deployment of package with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: mopper_env 
          channels: conda-forge, coecms
          channel-priority: true
          environment-file: conda/environment.yaml    # Path to the build conda environment
          auto-update-conda: false
          show-channel-urls: true #
      - name: Build but do not upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          meta_yaml_dir: conda
          python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
          user: coecms
          label: auto
          upload: false
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret
