name: mopper-all-tests

#on: [push]
on: 
  push:
    branches:
      - prerelease
      - main
  pull_request:
    branches:
      - main
      - prerelease
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v6.0.1
    - name: Set up Python 3.12/3.14
      uses: actions/setup-python@v6.1.10
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3.2.0
      with:
        activate-environment: testenv
        environment-file: conda/testenv.yaml
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Lint with ruff
      shell: bash -el {0}
      run: |
        ruff check --output-format=github .
      continue-on-error: true
     
    # making sure we are testing installed package
    - name: Install package
      shell: bash -el {0}
      run: |
        conda activate testenv
        pip install  -e .
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        conda run python -m pytest
        #conda run coverage run --source src -m py.test
   # - name: Upload to codecov 
   #   shell: bash -el {0}
   #   if: steps.build.outcome == 'success'
   #   run: |
   #     curl -Os https://uploader.codecov.io/latest/linux/codecov
   #     chmod +x codecov
   #     ./codecov

